### ISSUE TITLE
Symbol() overwrite

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#13]
@isiahmeadows Symbol is a reserved name, and you are overwriting it, before you are checking what it is.

```js
var Symbol = global.Symbol

var supportsRealSymbol = typeof Symbol === "function" &&
    typeof Symbol() === "symbol"
```

Remove this line, and it still pass
```js
var Symbol = global.Symbol
```

**Comment by isiahmeadows** [comment]
Actually, I'm not. That's specifically local to the file. CommonJS modules are executed in their own function scope, so that's not a problem.

This is moot with my latest push, though, because I found minor perf benefits to using the globals directly.
