### ISSUE TITLE
Typed array issues

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#19]
This two returns false, but should return true. Same tests as found for the nodeJS deepEqual algo.

```js
 [new Int16Array(256), new Uint16Array(256)], // should be true
[new Float64Array([+0.0]), new Float32Array([-0.0])], // should be true

```

@isiahmeadows For me both of them looks not identical so my opinion is that they should return false, but NodejS says different.

**Comment by isiahmeadows** [comment]
That's a no-go. Unsigned and signed numbers, as well as typed numbers of different widths should be considered different in my opinion, and any conversions should be explicit.

I'd have to disagree with the CommonJS standard's opinion on this one.
