### ISSUE TITLE
unused "mask"

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#22]
You are using "mask" in your code, but it doesn't seem to be dead code? Are you missing an variable?

**Comment by isiahmeadows** [comment]
Actually, that's a [bit field](https://en.wikipedia.org/wiki/Bit_field). It currently only has [3 flags](https://github.com/isiahmeadows/thallium/blob/d32ef1dc093eaee43f37448ce1e08c805e36dd87/lib/match.js#L80-L85), but it's mainly used to just keep the parameter count down and more structured.

Here's some examples of where it's used:

- [To find out if the match is strict](https://github.com/isiahmeadows/thallium/blob/d32ef1dc093eaee43f37448ce1e08c805e36dd87/lib/match.js#L394).
- [To find out if the match is at the top level, without adding an extra `initial` parameter to 4 different functions](https://github.com/isiahmeadows/thallium/blob/d32ef1dc093eaee43f37448ce1e08c805e36dd87/lib/match.js#L427).
- [To see if the objects are of the same prototype, without requiring an extra parameter](https://github.com/isiahmeadows/thallium/blob/d32ef1dc093eaee43f37448ce1e08c805e36dd87/lib/match.js#L540).

To be honest, it could probably be better named `context`.

**Comment by zubuzon** [comment]
I know it's a bit field, but it's not defined? It's only passed through for each function you are using?
I had expected something like `var mask 0x01`. But I can not find it defined somewhere in the source.

**Comment by isiahmeadows** [comment]
It's an argument to many of the functions, passed recursively throughout, but it starts from [these two functions](https://github.com/isiahmeadows/thallium/blob/94a91394ee3150a075c9fabb0e68240608a23ce5/lib/match.js#L87-L93). Note that I renamed it to `context` to be a little more specific as to its purpose.

**Comment by zubuzon** [comment]
Ah! Got it!

**Comment by isiahmeadows** [comment]
Welcome! Bit fields are very nice, concise immutable data structures, great for performance.

If you'd like, we can talk [in Gitter](https://gitter.im/isiahmeadows/thallium?utm_source=share-link&utm_medium=link&utm_campaign=share-link). I've had this room for a while.

(In case you're wondering, Gitter integrates with GitHub, and so you can use your sign-in from GitHub to sign into it. It's very nice.)

**Comment by zubuzon** [comment]
@isiahmeadows I'm on Gitter now. Private or public?

**Comment by zubuzon** [comment]
@isiahmeadows I left a couple of messages for you to read in a private chat on Gitter

**Comment by isiahmeadows** [comment]
@zubuzon I'm on Gitter now. Sorry for being away.

**Comment by zubuzon** [comment]
Is this relevant? I'm closing my "question".

**Comment by isiahmeadows** [comment]
The mask still exists, and is used. It's just a bit field I pass everywhere on the stack via function arguments. It merges a bunch of booleans I would otherwise need, and generally simplifies the code.
