### ISSUE TITLE
avoid symbol detection in Babel's `typeof` helper.

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#23]
Not familiar with Babel, so don't know how to fix this. Someone just told me that you should check for this.

**Comment by isiahmeadows** [comment]
I've already addressed this. Provided the polyfill is loaded first, it's [detected here](https://github.com/isiahmeadows/thallium/blob/master/lib/match.js#L75-L78) and [handled here](https://github.com/isiahmeadows/thallium/blob/master/lib/match.js#L75-L78). If Babel erroneously transpiles this, its polyfill will work appropriately, anyways.
