### ISSUE TITLE
object instance issues + solution

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#28]
Not sure how you want to fix this, but let us say you have this:

```js
  class BaseA {}
  class BaseB {}
  strict(new BaseA(), new BaseB()) // returns true, should have returned false
```
In the first example there are two different instances, and in strict mode it should be falsey.
A quick fix to solve this will be in your match function (*didn't check performance*)

```js
 if (typeof a !== 'object' || typeof b !== 'object') {
        return false;
 }
 
if (a.constructor !== b.constructor) {
        return false;
}

// now you will get correct result
```

@isiahmeadows The downsides of my solution is that object with it's own constructor property will be compared strictly as well. Take this example:

```js
strict({ 'constructor': [1] }, { 'constructor': [1] } // return false - with current code, this returns true
```

However, something like this isn't affected 

```js
strict({ 'constructor': 1 },   { 'constructor': '1' }) // returns true
```

but `1` vs `'1'` shouldn't be equal either in strict mode?

**Comment by isiahmeadows** [comment]
`match.strict({constructor: 1}, {constructor: '1'})` and `match.match({constructor: 1}, {constructor: '1'})` both should *always* return false, and I've verified this with a similar test. I'll reopen this if that's not the case, but for now, I'm closing.
