### ISSUE TITLE
fails when comparing primitives to composites

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#30]
@isiahmeadows Seems to fail when comparing primitives to composites

```js
strict(new String, {}) // returns true, should return false
strict({}, new String) // returns true, should return false

strict(new Number, {}) // returns true, should return false
strict({}, new Number) // returns true, should return false

strict(new Boolean, {}) // returns true, should return false
strict({}, new Boolean) // returns true, should return false

strict(new Date, {}) // returns true, should return false
strict({}, new Date) // returns true, should return false

```

**Comment by zubuzon** [comment]
@isiahmeadows I only see a few solution for this one, and both seems slow.

This one:
```js
strict(new Number, {})
```
will return false if you add a few more bytes inside the matchDifferentProto function.

```js
let aObjTString = objectToString.call(a);
if (aObjTString === '[object Number]') {
 return bObjTString === '[object Number]' && floatIs(+a, +b);
}
```
You can do the same with the rest, but should think of a much faster solution.

**Comment by zubuzon** [comment]
@isiahmeadows 

If you in your matchSameProto function add this too, you will also catch another bug

```js
 } else if (objectToString.call(a) === '[object Number]') {
      return a === b;
```
This will also solve this issue:

```js
new Object(NaN), new Object(NaN)) // returns true;
```
With my suggestion this NaN comparison (*two different instances*) will return false as expected

**Comment by zubuzon** [comment]
@isiahmeadows I solved this now locale, and discovered another thing. Your algo is failing on this benchmark test:

```js
 'number (differing)           ': [ new Number(123), new Number(456)],
```
With solution listed above, you can run this benchmark, and get this result:

```js
// before
number (differing)           :
~Fin~
// after
number (differing)            x 1,595,561 ops/sec ±3.46% (83 runs sampled)
```

**Comment by isiahmeadows** [comment]
Um...this is only the case for `t.match`, not `t.deepEqual`. Also, using the primitive wrappers are generally a bad idea, anyways, because they tend to cause more problems than they're worth. I may accept a PR provided it doesn't degrade performance, but I'm hesitant to implement it.
