### ISSUE TITLE
expando property issue

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#31]
@isiahmeadows  Look at the example. Returns true when it should return false.

```js
let a1= [1, 2, 3];
let a2 = [1, 2, 3];

a1.d = 1;
a2.c = 1;

strict(a1, a2) // returns true, but should have returned false;
```

**Comment by zubuzon** [comment]
@isiahmeadows I'm giving you a solution on this one too

In your matchSameProto function, under Array check, add this at the end  `return a === b;` , so the code looks like this

```js
  if (Array.isArray(a)) {

        if (a.length !== b.length) {
            return false;
        }
        if (a.length === 0) {
            return true;
        }
        return a === b;
    }

```

**Comment by isiahmeadows** [comment]
I intentionally pulled that support for performance, ease of implementation, and the relative lack of need. [See the changelog.](https://github.com/isiahmeadows/thallium/blob/master/CHANGELOG.md#v029)
