### ISSUE TITLE
remove one iteration loop

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#33]
In your matchInner function. You can swap

```js
// Shortcut if the properties are different.
    for (var i = 0; i < count; i++) {
        if (!hasOwn.call(b, akeys[i])) {
            return false;
        }
    }

    // Verify that all the akeys' values matched.
    for (var j = 0; j < count; j++) {
        if (!match(a[akeys[j]], b[akeys[j]], context, left, right)) {
            return false;
        }
    }

    return true;
```

with this

```js
// Shortcut if the properties are different.
    for (var i = 0; i < count; i++) {
        if (
          !hasOwn.call(b, akeys[i]) ||
          !match(a[akeys[i]], b[akeys[i]], context, left, right)
        ) {
            return false;
        }
    }

    return true;
```
"You can create an optimized path for specific known object signatures if you know them upfront but these generic variants are not optimized by VMs and requires lots of introspection into the internal hidden class representations to look up the keys in the respective class."

**Comment by isiahmeadows** [comment]
There's a few reasons I did that:

1. `hasOwn` is incredibly cheap. I'm almost surprised V8 doesn't emit raw assembly for it, as comparatively simple as it would likely be. 
2. V8 (as do most JIT engines for dynamically typed languages) uses inline caches for detecting type signatures. That means `hasOwnProperty` is no better than, say, `object.isValue`, or even nothing, for guarding types. These inline caches carry beyond the loop as well, so the engine already has the correct types going into the second loop.
3. Objects that are different fairly frequently have different keys, and it's cheap enough it hardly has a cost for the usual small object.

As for optimizing for signatures, I can't optimize for what I don't know, and the incoming object signatures are one thing I'll never know. And you may also be surprised to hear that [Lodash (for `isEqual`)](https://github.com/lodash/lodash/blob/master/lodash.js#L3256-L3297) and [Node (for `deepEqual`)](https://github.com/nodejs/node/blob/master/lib/assert.js#L215-L250) both use this optimization of verifying keys before values.
