### ISSUE TITLE
function detection issues in Safari

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#35]
@isiahmeadows In Safari typeof x === 'function' isn't enough. Safari 8-9 returns object for typed arrays and constructors, and Safari 10 issues with window.Proxy.

I noticed this when I was looking at lodash.

**Comment by zubuzon** [comment]
@isiahmeadows This function solves the bug

```js
function isFunction() {
 var tag = (value != null && (type == 'object' || type == 'function'))
 ? objectToString.call(value) 
  : '';
   return tag == '[object Function]'||
              tag == '[object GeneratorFunction]' ||
               tag == '[object Proxy]';
}
```

**Comment by zubuzon** [comment]
@isiahmeadows Not sure where you want to use such code, and this is slow I guess. So maybe only use this code for browser environment. There is no such bug in NodejS.

**Comment by isiahmeadows** [comment]
Feel free to send a pull request for that. You can detect this during module initialization in a fairly straightforward fashion, and do something like this (it'll almost undoubtedly get inlined in the latter):

```js
var isFunction = hasSafariBug
    ? function (value) {
        if (typeof value === "function") return value
        var tag = objectToString.call(value)

        return tag === "[object Function]" ||
            tag === "[object GeneratorFunction]" ||
            tag === "[object Proxy]"
    }
    : function (value) {
        return typeof value === "function"
    }
```

**Comment by isiahmeadows** [comment]
I don't have a Mac where I can readily test this, but I could fix that in Travis by fixing my build matrix (builds already take forever... :frowning:).

**Comment by isiahmeadows** [comment]
Mitigations in place as of abf1fa6.
