### ISSUE TITLE
Finish DOM reporter

### ISSUE THREAD

**Issue by isiahmeadows** [isiahmeadows/thallium#45]
There's been significant progress in this area, and you can find the existing source [here](https://github.com/isiahmeadows/thallium/blob/master/r/dom.js). It may only require modification and test coverage, which should be relatively easy to do.

**Comment by janga1997** [comment]
@isiahmeadows I want to claim this issue. Is there anything I should know?

**Comment by isiahmeadows** [comment]
@janga1997 You're just a little too late... I've just started finishing this myself. (It's mostly design now, but should be live within the next few days.) 😄
