### ISSUE TITLE
Add some promise-aware assertions

### ISSUE THREAD

**Issue by isiahmeadows** [isiahmeadows/thallium#51]
Pretty easy to do. Something like `assert.async` taking all the other `assert.*` methods, and applying them to the resolved promise instead. Example:

```js
// assert.async.equal
t.test(() => {
  assert.async.equal(doSomething(), 1)
})

// assert.equal equivalent
t.test(() => {
  return doSomething()
  .then(value => assert.equal(value, 1))
})
```

**Comment by janga1997** [comment]
@isiahmeadows I want to claim this issue. Is there anything else I need to know?

**Comment by isiahmeadows** [comment]
Sure! The assertions are located here (I just moved them out about a week or so ago): [clean-assert](https://github.com/isiahmeadows/clean-assert). I'd advise checking out [this CONTRIBUTING.md overview](https://github.com/isiahmeadows/thallium/blob/master/CONTRIBUTING.md#process-overview) and the [short contributing guide there](https://github.com/isiahmeadows/clean-assert#contributing) if you haven't already, but instead of forking and checking out Thallium (`https://github.com/<username>/thallium.git`), fork and check out clean-assert instead (`https://github.com/<username>/clean-assert.git`).

Also, a few items of mention:

- Most of the rest of that contributing guide does not apply.
- Unlike Thallium, it doesn't have the `node make ...` utility.
- Please expose it publicly as `clean-assert/async` and as `assert.async` from the main export. That was my initial plan, but I hadn't documented it anywhere yet.
- If, at any point, you have any questions, feel free to [ask on Gitter](https://gitter.im/isiahmeadows/thallium?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). I'm usually available to some extent all day.

**Comment by fxmaxvl** [comment]
Hi, here is my PR for async api feature
https://github.com/isiahmeadows/clean-assert/pull/2

welcome to review)

**Comment by isiahmeadows** [comment]
Closing per isiahmeadows/clean-assert#2.
