### ISSUE TITLE
Self-documenting assertion style using shorthand ES6 syntax and lambdas

### ISSUE THREAD

**Issue by rotemdan** [isiahmeadows/thallium#58]
As a long time user of libraries like Jasmine and Mocha, it seems like one of the most limiting factors of assertions like `expect(x).toEqual(y)` or `assert.equal(x,y)` is the fact that the variable names aren't documented in the error messages. Say I have four variables `a`, `b`, `c`, and `d` containing numbers and I want to assert multiple things about them. With most assertion styles I would do something like:

```ts
expect(a).toEqual(b);
// ...
expect(c).toEqual(d);
```
Now let's say that both these assertions failed, and it is possible that both `a` and `b` could have value `0` and `b` and `d` value `1`

Now I get the message:
```
Expected 0 to equal 1
```

How am I supposed to know which one of these assertion failed? Moreover, in practice it is usually not only two but sometimes gets to like 20 potential assertions that I have to figure out from. It may be that I'm "doing it wrong" and making too much assertions in one test, however "cramming" tons of assertions into one test is actually a style that seems most efficient to me in terms of the amount of effort to benefit it gives. 

Anyway, I thought about why not just use lambdas instead? In Javascript you can get the source code of any function using `func.toString()`. That source can be roughly parsed right? Also with some ES6 syntax we can get some really concise assertion statements that would be reasonably readable and "document" what is actually being asserted on:

```ts
let a, b, c, d;

// ..
// The object literal uses some ES6 shorthand notation here
expect({a, b}).toSatisfy(() => a === b);
expect({c, d}).toSatisfy(() => c === d);
```

`{c,d}` is an ES6 shorthand for `{c: c, d: d}`. So it gets both the names of the variables and their values in a simple, concise manner (Javascript objects preserve the order of insertion in `for .. in` so they can also be printed in the order they were stated in the code).

The argument to `expect` is only used to get more descriptive error messages. It isn't really needed, and it's properties aren't actually passed to the lambda (although they technically could, but there's no need really).

Using `.toString()` the source of the second lambda function would look like:

```ts
"function () { return c === d; }"
```

It is very easy to parse. And for the case the body of the function starts with the `return` keyword, it is easy to extract the predicate itself (the case where it doesn't begin with `return` could simply give the entire body of the function delimited in curly brackets `{ ... }`).

The error message could look something like:

```ts
Expected c = 0, d = 1 to satisfy c === d, 
```

In some cases that would be _tremendously_ more helpful than just `Expected 0 to equal 1`!
Also this allows for arbitrarily complex predicates of any arity that are very nicely self-documenting:

```ts
let a, b, c, d;

expect({a, b, c, d}).toSatisfy(() => a >= b && (b < c || a < d));
```
Error message:

```ts
Expected a = 5, b = 2, c = 1, d = -1 to satisfy a >= b && (b < c || a < d)
```

Or more realistically the variable names would be more meaningful:

```ts
Expected balanceBeforeTransaction = 51.23, balanceAfterTransaction = 52.34 to satisfy 
      balanceAfterTransaction > balanceBeforeTransaction 
```

**Comment by rotemdan** [comment]
This trick can also be used as an enhancement to the regular assertion style:

```ts
let a: number, b: number;

expect({a}).toEqual({b});
```
So now the testing library "knows" the first one is called `a` and second one `b`.
So it can print:
```
Expected a = 0 to equal b = 1
```

**Comment by rotemdan** [comment]
Alternative syntax:

```ts
let a: number; 
let b: number;
let c: number;
// ..
check({a, b, c}, () => a > sin(b) + cos(a));
// or just
assert({a, b, c}, () => c > sin(b) + cos(a));
```

It is also possible to verify that the properties specified in the first argument (`a`, `b` and `c`) are actually used in the lambda, for a basic form of checking :

1. Roughly. Just check the source of lambda's body contains them using a regular expression. This could have some false positives like if they are inside a string, but would still be useful.
2. Precisely. Using a lexical analyzer to get to rudimentary parse the body of the lambda.

A more advanced check would be to check that all variable identifiers in the lambda are declared in the object given, but that would be more complex.

By the way, I initially intended this for runtime assertions, and as an alternative to contracts. I'm very likely to implement this at some point (when I have time), probably also as an assertion library for Mocha.

**Comment by rotemdan** [comment]
_(I've edited the previous comment since it was sent so re-read if it wasn't clear)_

My initial intention was to have something similar to contracts that can be evaluated at "debug mode" but erased at "release mode" with negligible impact on performance (so the assertions can even be executed within a loop).

It turns out it's actually very easy to do this in Javascript:

```ts
const DEBUG = true;

let assert: (vars: { [varName: string]: any }, predicate: () => boolean) => void;

if (DEBUG) {
  assert = assertionFunction;
} else {
  assert = () => {};
}
```
I believe modern Javscript JITs should optimize the case where the function is empty to a no-op such that the assertion can even be included in a tight loop:

```ts
for (i=0; i< 1000000; i++) {
  // ...
  assert(...);
}
```

**Comment by rotemdan** [comment]
Another advantage of this assertion style is that it is possible to have a "verbose mode" that would print out individual assertions even if they pass (since the names of the checked identifiers are known to the library it would make a meaningful and readable log):

```ts
it("Does something with numbers", () => {
  let a: number;
  let b: number;
  let c: number;
  // ..
  assert({a, b}, () => a > b);
  assert({b, c}, () => b < c * 2);
  assert({a, c}, () => a >= sqrt(c));
}
...
```
And then the log might look like:
```
Does something with numbers:
✓ a = 2, b = 0 satisfy a > b
✓ b = 0, c = 2 satisfy b < c * 2
✓ a = 2, c = 2 satisfy a >= sqrt(c)
...
```

This could also help with the problem of "test rot" where tests become old and tiresome to maintain because the specification has changed or because different people come and go. It is also nice to see the values held by the referenced variables during the tests to identify issues in the assertions themselves and get ideas for additional ones.

It also reduces the need to have millions of:
```ts
it("Does something", () => {
 // 
})

it("Does the same but a tiny bit differently", () => {
 // 
})
```
Which can become bulky and eventually may reduce my personal motivation at writing detailed tests.

Another interesting advantage is that it is even possible to continue execution even if an assertion has thrown an error. Since the predicate is "locked" in an anonymous function, it is easy to just surround it with `try {..} catch (e){}`. Catch the error, print the message and continue.

```
Does something with numbers:
✗ a = 1, b = 2 satisfy a > b
✓ b = 2, c = 2 satisfy b < c * 2
✗ a = 1, c = 2 satisfy a >= sqrt(c)
...
```

**Comment by rotemdan** [comment]
I'm looking at a random real-world assertion I have, from a test. Currently it looks like this:
```ts
expect(await db.getLocalRevisions()).toEqual([]);
```
The problem with this is that if this fails I currently get something very uninformative, that doesn't even mention what the error is about:
```
expected ["a", "b"] to equal []
```

Since the subject here is not an identifier, I'm considering how it could be expressed in this assertion style. Maybe something like this:
```ts
assert({revisions: await db.getLocalRevisions()}, (revisions) => DeepEquals(revisions, []))
```
(The properties of the object given as first argument are passed to the anonymous function as arguments, in order).

Or something shorter like:

```ts
assert.equals({revisions: await db.getLocalRevisions()}, [])
```

Which would give the error:
```
expected revisions = ["a", "b"] to equal []
```

Or even better, if the assertions are internally numbered, it could add the index:

```
(5) expected revisions = ["a", "b"] to equal []
```

**Comment by isiahmeadows** [comment]
You can use literally any assertion library you want (Thallium doesn't care), provided it throws compatible `AssertionError` types. So if you want, I'd recommend just using Chai instead of the built-in `thallium/assert`. The only reason I actually package an assertion library with the framework is for those who don't want to find another assertion library just to use.

Also, I'm looking to move the assertion library itself out of core and just re-exporting it as a dependency (it'll still be `thallium/assert`, just aliased from elsewhere. It's not used anywhere else in this repo outside of the tests.

**Comment by isiahmeadows** [comment]
Oh, and I myself use the following idioms a lot:

```js
assert.match({foo, bar}, {
    foo: 1,
    bar: 2,
})
```

As for diffing, it's on the roadmap. :wink:

**Comment by rotemdan** [comment]
Hi, I guess I was misunderstood. I didn't really want to ask a question. Just wanted to suggest/discuss several things:

1. The idea and benefit of having named identifiers for the assertions targets, for better error messages.
2. Using anonymous function's bodies to better convey more complex predicates, and the potential for better documentation when extracting their internal code using reflection.
3. Using this information to provide a more detailed log about what happened within the running of the test (this is a feature that's more about the test runner than the assertion library).

I'm confused, I'm not sure how this relates to Chai, `assert.match` or diffing?

**Comment by isiahmeadows** [comment]
If you want something that powerful, I'd recommend [`power-assert`](https://github.com/power-assert-js/power-assert), and I'm not about to try to replicate that. Your very use case is why they created it.

Also, do note that in order to use power-assert, you have to transform your code, and the easiest way to use that with Thallium is to transform your code with the relevant Babel plugin (linked there). Currently, the assertions may print out a bit oddly ([known issue](https://github.com/isiahmeadows/thallium/issues/59)), but it's been lower priority for me (but fixing it would be really helpful). I plan to cut a patch soon.

If you need to, you can add a `.tl.opts` in your project root with the following line:

```
--require js:babel-register
```

**Comment by rotemdan** [comment]
Hi, this was never intended to be a feature request! I even mentioned that I intend to implement it myself at some point. Just something I had in mind that I thought would interest you, I guess since you wrote an testing library!

I'm not sure if code transformation is the path I want to go to, for a large part because I initially wanted this to be used for code contracts, so it doesn't isn't reasonable to require a transform to all code that uses it. Also, this isn't just something just for myself. I'm thinking about something that can fit everyone and would be easy to use. The examples I gave were the best implementation approaches I found so far. I just thought you might have ideas on how to improve this.

**Comment by rotemdan** [comment]
Looking in my own test suites,

Maybe the problem is that the type of assertions used with contracts and unit testing are actually quite different in nature:

In contracts, it is unlikely that the assertion would be over a function call like:
```ts
assert.Equals(getValueFromDatabase(), ...)
```
However in unit tests it isn't less common to have assertions that include complex clauses and multiple variables like:
```
num > 0 && num < 10 && isInteger(num) && num > otherNum * 2
```
Etc.

So maybe I should concentrate on contracts for now, and once I have it in place there I'll come back to unit tests.

**Comment by isiahmeadows** [comment]
First, I didn't read the whole thing first (massive walls of text). Sorry for the confusion! And no, this won't land in core, at least initially.

But I do have a few tips:

1. Create a common engine for mapping the API to something you can actually verify and print. This separates the test, your assertion, as well as the messages, what you'll need to generate, from the API, which has a fair amount of abstraction within it. In particular, most BDD assertion libraries like Chai have such an engine within it to abstract away the actual conditional testing from the fluent API.

2. If you want custom test names, write your library [as a plugin](https://github.com/isiahmeadows/thallium/blob/master/docs/plugins.md), and use `reflect.test` so you can run the assertions within it and name the tests accordingly. Oh, and do provide a way to skip tests.

**Comment by rotemdan** [comment]
Hi, again I wanted to interest you in some idea and get feedback, not request anything! (nothing should "land" anywhere I don't even use Thallium, I just found about it yesterday!)

I wrote a lot because I felt I needed to provide as much information as possible to explain this.

I thought it would interest you to think about how to improve and innovate test assertions and testing in general. This seems like the right place to post it. I'm sorry if it didn't catch your interest. I thought it would because it highlights some shortcoming of exiting approaches to this area, and has impact on the test runner as well (for example being able to log individual assertion results - there is no point of doing this if the messaged don't provide enough reasonable information for human to understand them).

I thought this would be a place where it is possible to think about the subject creatively maybe. Maybe my idea isn't good enough (at least for unit testing - maybe it works better for contracts). That's okay, I'll come back if I have better ideas.

**Comment by isiahmeadows** [comment]
@rotemdan This kind of thing would be much easier to talk about in [Gitter](https://gitter.im/isiahmeadows/thallium). So feel free to join me there. :wink:

**Comment by rotemdan** [comment]
Thanks for the offer but I personally prefer writing longer messages, in longer intervals, because it gives me enough time to think about things. Enough space to write examples etc. Also the having code highlighting helps, being able to edit later etc.

I sometimes get "grabbed" on a subject I feel like I need to figure it out quickly and move on. This is sort of the state now. I need to go do some other things so I'm trying to get to a point where I can let it go as fast as I can.. This translates to writing 5 messages in a row and walls of text.. sorry about that :)

**Comment by isiahmeadows** [comment]
Okay. I understand. You're okay. Feel free to move fast and break things, then! Come up with something great! :smile:

**Comment by isiahmeadows** [comment]
Oh, and I like keeping a TODO list psuedo-roadmap in my repos, because that helps me a lot without littering everywhere else. I've kind of got something like that going on in a newer utility I'm focusing more on.

**Comment by isiahmeadows** [comment]
ATM, I'm splitting everything up now, to break up this pseudo-modular monorepo (all under one package).

**Comment by rotemdan** [comment]
I signed into gitter to the link you gave. I've never used it before.

**Comment by rotemdan** [comment]
Here's a very basic implementation I wrote in 10 minutes (for illustration). It doesn't yet correctly parse the source of the function in different cases (`function () { return ... }` pattern, arrow function (`() => ...`) etc., object destructuring in a parameter (`function ({bla}) { return .. }`) etc.). It uses some utility functions I omitted here (`log`, `createErrorMessage`) because they are not important.

```ts
export function assert<T extends { [argName: string]: any }>(args: T, predicate: (args: T) => boolean): void {
	const getPredicateFunctionBody = () => {
		const predicateSource = predicate.toString();
		const predicateBody = predicateSource.substr(predicateSource.indexOf("{"));
		return predicateBody;
	}

	const getFormattedArgs = (): string => {
		let formattedArgs = "";

		let first = true;

		for (const arg in args) {
			if (!first)
				formattedArgs += ", "

			formattedArgs += `${arg} = ${JSON.stringify(args[arg])}`;
			first = false;
		}

		return formattedArgs;
	}

	let result: boolean;

	try {
		result = predicate(args);
	} catch (e) {
		const errorMessage = `Assertion throwed: ${getFormattedArgs()} errored when checked for ${getPredicateFunctionBody()}. Error: ${createErrorMessage(e)}`;
		log(errorMessage);
		return;
	}

	if (result === false) {
		const errorMessage = `Assertion failed: ${getFormattedArgs()} failed to satisfy ${getPredicateFunctionBody()}`;
		log(errorMessage);
	}
}
```

That's all there is to it! Really.. Sorry I made it look more complex than it really is.

Real world usage examples:
```ts
assert({host}, () => host.length > 10);
```
```ts
assert({metadata: row.entry.metadata}, ({metadata}) => metadata != null);
```

Example error messages:
```
Assertion throwed: host = "http://10.0.0.100:8002/datastore/test.config" errored when checked for 
{ return host["sadfsda"]["a"] > 500000; }. Error: Unhandled exception: TypeError: host.sadfsda is undefined
```
```
Assertion failed: metadata = {"updateTime":1483642949853610,"commitTime":1483642953088125}
failed to satisfy { return metadata == null; }
```

I'm trying to get you excited about contracts/assertions again! :) Who knows? Maybe someday you'll write an assertion/testing library of your own (oh wait..).

**Comment by isiahmeadows** [comment]
@rotemdan Interesting! Here's a few more ideas:

1. Trim the assertion message to include the function body instead of just the whole function. For example, `host.length > 10` is probably a little more helpful than `() => host.length > 10`.
2. Throw [`AssertionError` instances](https://www.npmjs.com/package/assertion-error) instead of logging errors. It's much more portable that way.
3. Consider the case of bound functions and non-arrow functions (e.g. ES5 functions, object methods).
4. Make a repo about it and tell people about the idea. There's bound to be many people that would appreciate this.

**Comment by isiahmeadows** [comment]
@rotemdan 

> I'm trying to get you excited about contracts/assertions again! :) Who knows? Maybe someday you'll write an assertion/testing library of your own (oh wait..).

:smile:
