### ISSUE TITLE
circular reference issues

### ISSUE THREAD

**Issue by crazyhuggins** [isiahmeadows/thallium#6]
Your assertion library - equals - doesn't handle circular reference.  **RangeError: Maximum call stack size exceeded**

**Comment by crazyhuggins** [comment]
There are both circular issues with Objects and arrays.

**Comment by isiahmeadows** [comment]
I largely adapted it from [deep-equal](https://www.npmjs.com/package/deep-equal), which also has the same issue (Chai does, too). I think Node is one of few that *doesn't* have this problem (i.e. memoizes the objects it checks).

**Comment by isiahmeadows** [comment]
Fixed
