### ISSUE TITLE
Windows failures again...

### ISSUE THREAD

**Issue by isiahmeadows** [isiahmeadows/thallium#60]
- ~~[Globs are very wrong](https://ci.appveyor.com/project/isiahmeadows/thallium/build/163/job/pjfvd71lsm1233y5#L1307)~~ Fixed in #61.
- [Stack traces are incorrectly trimmed](https://ci.appveyor.com/project/isiahmeadows/thallium/build/163/job/pjfvd71lsm1233y5#L1920)
- Other things, maybe?

**Comment by isiahmeadows** [comment]
Anyone with a working Windows installation should be able to do this with little effort. (I can point you to where you need to look.)

**Comment by fortMaximus** [comment]
I would like to contribute. I'm new to GitHub and Contribution.

**Comment by isiahmeadows** [comment]
@fortMaximus 

1. Thanks for offering! I do deeply appreciate it.
1. If you haven't already, [please read this](https://github.com/isiahmeadows/thallium/blob/master/CONTRIBUTING.md). It contains a lot of useful info on how to get started as well as the contribution process here.
1. Here's the relevant files you'll probably want to look first at:
    - The glob code is here, about 2/3 of the way down: [`lib/cli/loader.js`](https://github.com/isiahmeadows/thallium/blob/master/lib/cli/loader.js)
    - The stack traces in question are near the top of this file: [`lib/reporter/console-reporter.js`](https://github.com/isiahmeadows/thallium/blob/master/lib/reporter/console-reporter.js)
1. I'll note that until now, this project has been almost exclusively me on my own. So don't be entirely surprised if there's a few under-commented places (although it's large enough I kind of have to comment a bit just so I'm not looking at it like it grew eyes, nose, a mouth, legs, and started breathing nasal demons :smile:). If you have questions, feel free to ask me here. I'm generally available.

**Comment by isiahmeadows** [comment]
Given the urgency of the situation, I'm fixing the glob half. So it's now just the stacks.

**Comment by isiahmeadows** [comment]
#61 was only a partial fix, hence the re-open.

**Comment by isiahmeadows** [comment]
Fixed in 051dbd5.
