### ISSUE TITLE
regExp equal check fails

### ISSUE THREAD

**Issue by crazyhuggins** [isiahmeadows/thallium#7]
regExp equal check fails.

Just test if  `/Moe/gim` is equal to `/Curly/gim`, and the match is positive!!

**Comment by isiahmeadows** [comment]
Fixed.

**Comment by isiahmeadows** [comment]
To clarify, it's fixed for `deepEqual`, `deepEqualLoose`, and `match`.

Note that `equal` and `notEqual` have the behavior of ES2015 `Object.is`
(`NaN`s are equal, strict equality otherwise). So if `t.equal(/foo/,
/foo/)` doesn't throw, it's a bug.
