### ISSUE TITLE
help-simple.txt' doesn't exist

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#9]
Hi

I was just trying to see if I could use this project for testing client works, but found out it's not working at all. The CLI is broken. Trying to find a help-simple.txt' file that doesnt exist in the bin folder
```js
Error: ENOENT: no such file or directory, open ...node_modules\thallium\bin\help-simple.txt'
```

**Comment by isiahmeadows** [comment]
Don't have this issue on Linux, and I don't feed it raw paths. If you can find the bug, please file a PR! (I haven't gotten this tested on Windows yet.)

**Comment by zubuzon** [comment]
Im driving now and a funeral tomorrow so no time now, but this happened
when i installed from NPM. From my memory i think i figured out that NPM
has an older version and you refactored CLI after latest NPM push

**Comment by zubuzon** [comment]
This bug will fix itself if you push katest build to npm. An old version there now.

**Comment by zubuzon** [comment]
Try test it yourself. NPM install thallium in a empty repo.

**Comment by isiahmeadows** [comment]
Closing, since this bug is fixed.

**Comment by isiahmeadows** [comment]
[Nope, it's not.](https://github.com/isiahmeadows/thallium/blob/master/bin/thallium.js#L17-L18).
